name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Runs release-please to determine if a release is needed and create a release PR
      - uses: googleapis/release-please-action@v4
        id: release
      # The logic below handles the github package registry publication
      # the if statements ensure that a publication only occurs when a new release is created:
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.releases_created == 'true' }}
      - uses: actions/setup-node@v4
        if: ${{ steps.release.outputs.releases_created == 'true' }}
        with:
          node-version: 22
          registry-url: https://npm.pkg.github.com/
      - run: npm install -g pnpm
        if: ${{ steps.release.outputs.releases_created == 'true' }}
      - run: pnpm install --frozen-lockfile
        if: ${{ steps.release.outputs.releases_created == 'true' }}
      - run: pnpm publish -r --access public
        if: ${{ steps.release.outputs.releases_created == 'true' }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}